/* Mix Chicken Gestão — versão profissional
   Compatível com os dados anteriores armazenados em localStorage na chave mixPro.
   Não altera a estrutura dos cadastros antigos: adiciona campos quando necessário.
*/
const DEMO={
 config:{labor:5200,fixed:2800,target:20000},
 financeCategories:{
  entrada:["Dinheiro","Cartão","Pix","Goomer","iFood","WhatsApp","Outros"],
  saida:["Mercado","Boletos","Park Container","Freelancer","Juros","Coolt","Taon","Contabilidade","Copel","Internet","Outros"]
 },
 ingredients:[
  {id:1,name:"Filé de frango",category:"Alimentos",unit:"kg",price:18.9,supplier:"Atacado",stock:32,min:10,grossWeight:1,netWeight:1,grossValue:18.9,netValue:18.9,marketPrices:[{supplier:"Atacado",price:18.9},{supplier:"Mercado Central",price:19.5},{supplier:"Distribuidora Sul",price:18.2}]},
  {id:2,name:"Batata congelada",category:"Alimentos",unit:"kg",price:12.5,supplier:"Distribuidor",stock:25,min:8,grossWeight:1,netWeight:1,grossValue:12.5,netValue:12.5,marketPrices:[]},
  {id:3,name:"Linguiça de frango",category:"Alimentos",unit:"kg",price:21.9,supplier:"Atacado",stock:12,min:5,grossWeight:1,netWeight:1,grossValue:21.9,netValue:21.9,marketPrices:[]},
  {id:4,name:"Farinha de trigo",category:"Alimentos",unit:"kg",price:6.8,supplier:"Atacado",stock:9,min:4,grossWeight:1,netWeight:1,grossValue:6.8,netValue:6.8,marketPrices:[]},
  {id:5,name:"Óleo de soja",category:"Alimentos",unit:"L",price:7.9,supplier:"Atacado",stock:18,min:6,grossWeight:1,netWeight:1,grossValue:7.9,netValue:7.9,marketPrices:[]},
  {id:6,name:"Gochujang",category:"Alimentos",unit:"kg",price:39.9,supplier:"Importados",stock:2.5,min:1,grossWeight:1,netWeight:1,grossValue:39.9,netValue:39.9,marketPrices:[]},
  {id:7,name:"Molho de laranja",category:"Alimentos",unit:"kg",price:22,supplier:"Produção própria",stock:3,min:1,grossWeight:1,netWeight:1,grossValue:22,netValue:22,marketPrices:[]},
  {id:8,name:"Muçarela",category:"Alimentos",unit:"kg",price:34.9,supplier:"Laticínios",stock:5,min:2,grossWeight:1,netWeight:1,grossValue:34.9,netValue:34.9,marketPrices:[]}
 ],
 products:[
  {id:1,name:"TRIO",price:45,recipe:[{i:1,q:.18},{i:3,q:.15},{i:2,q:.25}],sold:96,image:"",description:"Trio de frango, linguiça e batata.",laborCost:0,packagingCost:0,yield:1},
  {id:2,name:"Frango Supremo",price:85,recipe:[{i:1,q:.65},{i:4,q:.08},{i:5,q:.04}],sold:72,image:"",description:"Porção de frango empanado.",laborCost:0,packagingCost:0,yield:1},
  {id:3,name:"Korean Chicken",price:59.9,recipe:[{i:1,q:.45},{i:6,q:.06},{i:4,q:.06},{i:5,q:.03}],sold:58,image:"",description:"Frango frito com molho gochujang.",laborCost:0,packagingCost:0,yield:1},
  {id:4,name:"Orange Chicken",price:59.9,recipe:[{i:1,q:.45},{i:7,q:.08},{i:4,q:.06},{i:5,q:.03}],sold:44,image:"",description:"Frango frito com molho de laranja.",laborCost:0,packagingCost:0,yield:1},
  {id:5,name:"Porção Mista G",price:72,recipe:[{i:1,q:.4},{i:3,q:.2},{i:2,q:.25}],sold:51,image:"",description:"Porção mista grande.",laborCost:0,packagingCost:0,yield:1},
  {id:6,name:"Porção Frango Empanado G",price:79,recipe:[{i:1,q:.65},{i:4,q:.08},{i:5,q:.04}],sold:63,image:"",description:"Frango empanado grande.",laborCost:0,packagingCost:0,yield:1},
  {id:7,name:"Mac & Cheese + Frango",price:36.9,recipe:[{i:1,q:.16},{i:8,q:.06},{i:4,q:.03}],sold:39,image:"",description:"Macarrão cremoso com frango.",laborCost:0,packagingCost:0,yield:1}
 ],
 sales:[
  {id:1,date:"2026-08-20",product:1,qty:5},{id:2,date:"2026-08-20",product:3,qty:3},{id:3,date:"2026-08-19",product:2,qty:2},{id:4,date:"2026-08-19",product:5,qty:4},{id:5,date:"2026-08-18",product:4,qty:3},{id:6,date:"2026-08-18",product:7,qty:5}
 ],
 transactions:[
  {id:1,date:"2026-08-20",dueDate:"2026-08-20",type:"entrada",cat:"Vendas",paymentMethod:"Pix",desc:"Vendas do dia",value:1240,status:"pago"},
  {id:2,date:"2026-08-19",dueDate:"2026-08-19",type:"entrada",cat:"Vendas",paymentMethod:"Cartão",desc:"Vendas do dia",value:980,status:"pago"},
  {id:3,date:"2026-08-18",dueDate:"2026-08-18",type:"entrada",cat:"Vendas",paymentMethod:"Dinheiro",desc:"Vendas do dia",value:1120,status:"pago"},
  {id:4,date:"2026-08-18",dueDate:"2026-08-18",type:"saida",cat:"Insumos",paymentMethod:"Pix",desc:"Compra de frango",value:540,status:"pago"},
  {id:5,date:"2026-08-17",dueDate:"2026-08-17",type:"saida",cat:"Insumos",paymentMethod:"Pix",desc:"Compra de batata",value:280,status:"pago"},
  {id:6,date:"2026-08-15",dueDate:"2026-08-15",type:"saida",cat:"Mão de obra",paymentMethod:"Dinheiro",desc:"Folha",value:5200,status:"pago"},
  {id:7,date:"2026-08-10",dueDate:"2026-08-10",type:"saida",cat:"Despesas",paymentMethod:"Pix",desc:"Energia",value:780,status:"pago"}
 ],
 purchases:[]
};
let raw=localStorage.getItem("mixPro"),S=raw?JSON.parse(raw):structuredClone(DEMO);
let charts={},zoomState={},customStart=null,customEnd=null;
const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(n)||0);
const pct=n=>(Number(n)||0).toFixed(1).replace(".",",")+"%";
const esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]));
const today=()=>new Date().toISOString().slice(0,10);
const ing=id=>S.ingredients.find(x=>x.id==id);
const prod=id=>S.products.find(x=>x.id==id);
const cost=p=>(p.recipe||[]).reduce((a,r)=>a+(ing(r.i)?.price||0)*Number(r.q||0),0);
const cmo=p=>Number(p.laborCost||0)+Number(p.packagingCost||0);
const totalProductCost=p=>cost(p)+cmo(p);
const cmv=p=>p.price?cost(p)/p.price*100:0;
const markup=p=>totalProductCost(p)?p.price/totalProductCost(p):0;
const margin=p=>p.price-totalProductCost(p);
function save(){localStorage.setItem("mixPro",JSON.stringify(S));}
function migrate(){
 S.config=S.config||structuredClone(DEMO.config);
 S.financeCategories=S.financeCategories||structuredClone(DEMO.financeCategories);
 S.ingredients=S.ingredients||[];S.products=S.products||[];S.sales=S.sales||[];S.transactions=S.transactions||[];S.purchases=S.purchases||[];
 S.ingredients.forEach(i=>{i.category=i.category||"Alimentos";i.grossWeight=Number(i.grossWeight??1);i.netWeight=Number(i.netWeight??i.grossWeight??1);i.grossValue=Number(i.grossValue??i.price??0);i.netValue=Number(i.netValue??i.price??0);i.marketPrices=i.marketPrices||[];});
 S.products.forEach(p=>{p.description=p.description||"";p.laborCost=Number(p.laborCost||0);p.packagingCost=Number(p.packagingCost||0);p.yield=Number(p.yield||1);});
 S.transactions.forEach(t=>{t.dueDate=t.dueDate||t.date;t.status=t.status||((new Date(t.dueDate)<=new Date())?"pago":"pendente");t.paymentMethod=t.paymentMethod||((t.type==="entrada")?"Outros":"Outros");});
 save();
}
migrate();
const nav=[["dashboard","⌂","Início"],["vendas","＋","Vendas"],["financeiro","R$","Financeiro"],["compras","▤","Compras"],["insumos","◫","Insumos"],["estoque","□","Estoque"],["fichas","⚖","Fichas"],["produtos","☷","Produtos"],["relatorios","▥","Relatórios"],["vendasproduto","📊","Vendas mês"],["config","⚙","Config"]];
function buildNav(){
 $("sideNav").innerHTML=nav.map(n=>`<button class="navbtn" data-go="${n[0]}">${n[1]} <span>${n[2]}</span></button>`).join("");
 $("bottomNav").innerHTML=nav.slice(0,5).map(n=>`<button data-go="${n[0]}"><span class="nav-icon">${n[1]}</span>${n[2]}</button>`).join("")+`<button data-go="mais"><span class="nav-icon">•••</span>Mais</button>`;
 document.querySelectorAll("[data-go]").forEach(x=>x.onclick=()=>go(x.dataset.go));
}
function go(id){if(id==="mais")id="estoque";document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===id));document.querySelectorAll("[data-go]").forEach(x=>x.classList.toggle("active",x.dataset.go===id));$("title").textContent=({dashboard:"Dashboard",vendas:"Vendas",financeiro:"Financeiro",compras:"Compras",insumos:"Insumos",estoque:"Estoque",fichas:"Fichas técnicas",produtos:"Produtos",relatorios:"Relatórios",vendasproduto:"Vendas por produto",config:"Configurações"})[id]||"Gestão";render();}
function toast(x){const t=$("toast");t.textContent=x;t.classList.add("show");clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove("show"),2400);}
function modal(title,body,cb){$("modalTitle").textContent=title;$("form").innerHTML=body;$("modal").classList.remove("hidden");$("form").onsubmit=e=>{e.preventDefault();cb(new FormData(e.target));close();};}
function close(){$("modal").classList.add("hidden");}
$("close").onclick=close;
function periodTx(){const sel=$("period").value;if(sel==="-1"&&customStart&&customEnd){return S.transactions.filter(t=>t.date>=customStart&&t.date<=customEnd);}let d=+sel,start=new Date();start.setDate(start.getDate()-d);return S.transactions.filter(t=>new Date(t.date)>=start);}
function salesInRange(){const sel=$("period").value;if(sel==="-1"&&customStart&&customEnd)return S.sales.filter(s=>s.date>=customStart&&s.date<=customEnd);let d=+sel,start=new Date();start.setDate(start.getDate()-d);return S.sales.filter(s=>new Date(s.date)>=start);}
function revenueFromSales(arr){return arr.reduce((a,s)=>a+(prod(s.product)?.price||0)*s.qty,0);}
function destroyCharts(){Object.values(charts).forEach(c=>{try{c.destroy()}catch(e){}});charts={};}
function dashboard(){
 const tx=periodTx(),salesArr=salesInRange();
 const rev=tx.filter(t=>t.type==="entrada").reduce((a,t)=>a+Number(t.value),0)||revenueFromSales(salesArr);
 const purchases=tx.filter(t=>t.type==="saida"&&(t.cat==="Insumos"||t.cat==="Compras")).reduce((a,t)=>a+Number(t.value),0);
 const labor=tx.filter(t=>t.type==="saida"&&["Mão de obra","Freelancer"].includes(t.cat)).reduce((a,t)=>a+Number(t.value),0);
 const out=tx.filter(t=>t.type==="saida").reduce((a,t)=>a+Number(t.value),0),profit=rev-out;
 $("mRevenue").textContent=money(rev);$("mCMV").textContent=pct(rev?purchases/rev*100:0);$("mCMVSub").textContent=money(purchases);$("mCMO").textContent=pct(rev?labor/rev*100:0);$("mCMOSub").textContent=money(labor);$("mMargin").textContent=pct(rev?profit/rev*100:0);$("mMarginSub").textContent=money(profit);$("mTicket").textContent=money(salesArr.length?revenueFromSales(salesArr)/salesArr.reduce((a,s)=>a+s.qty,0):0);$("mOrders").textContent=salesArr.reduce((a,s)=>a+s.qty,0)+" unidades";
 $("alerts").innerHTML=S.ingredients.filter(i=>i.stock<=i.min).map(i=>`<div class="alert"><span>${esc(i.name)}</span><b>${i.stock} ${esc(i.unit)}</b></div>`).join("")||`<p class="muted">Nenhum item crítico.</p>`;
 const sel=$("dashboardProductCompare");if(sel){const current=sel.value;sel.innerHTML=S.products.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join("");if(current)sel.value=current;}
 destroyCharts();
 const labels=["-5","-4","-3","-2","-1","Atual"],base=rev||6000;
 charts.s=new Chart($("salesChart"),{type:"line",data:{labels,datasets:[{label:"Faturamento",data:labels.map((_,i)=>base*(.72+i*.056)),tension:.3},{label:"Custos",data:labels.map((_,i)=>(out||base*.6)*(.72+i*.055)),tension:.3}]},options:{responsive:true,plugins:{legend:{position:"bottom"}}}});
 charts.c=new Chart($("costChart"),{type:"doughnut",data:{labels:["CMV/Compras","CMO","Outras despesas"],datasets:[{data:[purchases,labor,Math.max(0,out-purchases-labor)]}]},options:{plugins:{legend:{position:"bottom"}}}});
 const map={};salesArr.forEach(s=>map[s.product]=(map[s.product]||0)+s.qty);const sorted=Object.entries(map).sort((a,b)=>b[1]-a[1]).slice(0,8);charts.t=new Chart($("topChart"),{type:"bar",data:{labels:sorted.map(([id])=>prod(id)?.name||"—"),datasets:[{label:"Unidades",data:sorted.map(([,q])=>q)}]},options:{indexAxis:"y",plugins:{legend:{display:false}}}});
 const purchaseByMonth={};S.purchases.forEach(p=>{const m=p.date.slice(0,7);purchaseByMonth[m]=(purchaseByMonth[m]||0)+p.q*p.unit;});const salesByMonth={};S.sales.forEach(s=>{const m=s.date.slice(0,7);salesByMonth[m]=(salesByMonth[m]||0)+(prod(s.product)?.price||0)*s.qty;});const months=[...new Set([...Object.keys(purchaseByMonth),...Object.keys(salesByMonth)])].sort().slice(-6);charts.purchase=new Chart($("purchaseVsSalesChart"),{type:"bar",data:{labels:months.length?months:[new Date().toISOString().slice(0,7)],datasets:[{label:"Vendas",data:months.map(m=>salesByMonth[m]||0)},{label:"Compras de insumos",data:months.map(m=>purchaseByMonth[m]||0)}]},options:{responsive:true,plugins:{legend:{position:"bottom"}}}});
 const cp=Number($("dashboardProductCompare")?.value||S.products[0]?.id);renderProductCompare(cp);
}
function renderProductCompare(pid){const p=prod(pid),ctx=$("productCompareChart");if(!p||!ctx)return;const now=new Date();const months=[];for(let i=5;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1);months.push(d.toISOString().slice(0,7));}const data=months.map(m=>S.sales.filter(s=>s.product==pid&&s.date.slice(0,7)===m).reduce((a,s)=>a+s.qty,0));if(charts.pc)charts.pc.destroy();charts.pc=new Chart(ctx,{type:"line",data:{labels:months,datasets:[{label:`Unidades — ${p.name}`,data,tension:.3}]},options:{responsive:true,plugins:{legend:{position:"bottom"}}}});}
function sales(){const ts=S.sales.filter(s=>s.date===today()),r=revenueFromSales(ts),q=ts.reduce((a,s)=>a+s.qty,0);$("todayRevenue").textContent=money(r);$("todayOrders").textContent=q;$("todayTicket").textContent=money(q?r/q:0);const search=($("saleSearch").value||"").toLowerCase();$("salesTable").innerHTML=S.sales.slice().reverse().filter(s=>(prod(s.product)?.name||"").toLowerCase().includes(search)).map(s=>{const p=prod(s.product),tot=(p?.price||0)*s.qty;return `<tr><td>${s.date}</td><td>${esc(p?.name||"—")}</td><td>${s.qty}</td><td>${money(p?.price)}</td><td>${money(tot)}</td><td>${pct(cmv(p||{price:0}))}</td><td><button class="icon-btn delete" onclick="delSale(${s.id})">×</button></td></tr>`}).join("");}
function finance(){
 const ins=S.transactions.filter(t=>t.type==="entrada").reduce((a,t)=>a+Number(t.value),0),out=S.transactions.filter(t=>t.type==="saida").reduce((a,t)=>a+Number(t.value),0),due=S.transactions.filter(t=>t.type==="saida"&&t.status!=="pago").reduce((a,t)=>a+Number(t.value),0);$("finIn").textContent=money(ins);$("finOut").textContent=money(out);$("finNet").textContent=money(ins-out);$("finDue").textContent=money(due);
 const search=($("txSearch").value||"").toLowerCase();$("txTable").innerHTML=S.transactions.slice().sort((a,b)=>b.date.localeCompare(a.date)).filter(t=>(`${t.desc} ${t.cat} ${t.paymentMethod}`).toLowerCase().includes(search)).map(t=>`<tr><td>${t.date}</td><td>${t.dueDate||t.date}</td><td>${t.type==="entrada"?"Entrada":"Saída"}</td><td>${esc(t.cat)}</td><td>${esc(t.paymentMethod||"Outros")}</td><td>${esc(t.desc)}</td><td><button class="status-btn ${t.status==="pago"?"paid":"pending"}" onclick="toggleTxStatus(${t.id})">${t.status==="pago"?"Pago":"Pendente"}</button></td><td class="${t.type==="entrada"?"positive":"negative"}">${money(t.value)}</td><td><button class="icon-btn delete" onclick="delTx(${t.id})">×</button></td></tr>`).join("");
 const em={};S.transactions.filter(t=>t.type==="entrada").forEach(t=>em[t.paymentMethod||"Outros"]=(em[t.paymentMethod||"Outros"]||0)+Number(t.value));$("revenueMethods").innerHTML=Object.entries(em).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="indicator"><span>${esc(k)}</span><b>${money(v)}</b></div>`).join("")||`<p class="muted">Nenhuma entrada.</p>`;
 const ec={};S.transactions.filter(t=>t.type==="saida").forEach(t=>ec[t.cat]=(ec[t.cat]||0)+Number(t.value));$("expenseCategories").innerHTML=Object.entries(ec).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="indicator"><span>${esc(k)}</span><b>${money(v)}</b></div>`).join("")||`<p class="muted">Nenhuma despesa.</p>`;
 planner();
}
function planner(){let base=$("plannerWeek").value;if(!base)base=today();const d=new Date(base+"T12:00:00"),day=d.getDay(),monday=new Date(d);monday.setDate(d.getDate()-(day===0?6:day-1));const names=["Seg","Ter","Qua","Qui","Sex","Sáb","Dom"];let html="";for(let i=0;i<7;i++){const x=new Date(monday);x.setDate(monday.getDate()+i);const ds=x.toISOString().slice(0,10),tx=S.transactions.filter(t=>(t.date===ds||t.dueDate===ds));const inV=tx.filter(t=>t.type==="entrada").reduce((a,t)=>a+Number(t.value),0),outV=tx.filter(t=>t.type==="saida").reduce((a,t)=>a+Number(t.value),0),pending=tx.filter(t=>t.type==="saida"&&t.status!=="pago").reduce((a,t)=>a+Number(t.value),0);html+=`<article class="day-card"><b>${names[i]}</b><small>${ds.split("-").reverse().slice(0,2).join("/")}</small><span class="positive">+ ${money(inV)}</span><span class="negative">− ${money(outV)}</span><strong>Saldo ${money(inV-outV)}</strong><em>${pending?money(pending)+" a vencer":"Nada a vencer"}</em></article>`;}$("weeklyPlanner").innerHTML=html;}
function ingredients(){const q=($("ingredientSearch").value||"").toLowerCase();$("ingredientTable").innerHTML=S.ingredients.filter(i=>(`${i.name} ${i.supplier} ${i.category}`).toLowerCase().includes(q)).map(i=>{const prices=i.marketPrices||[];const best=[{supplier:i.supplier,price:i.price},...prices].filter(x=>x.supplier&&x.price>0).sort((a,b)=>a.price-b.price)[0];return `<tr><td>${esc(i.name)}</td><td>${esc(i.category)}</td><td>${esc(i.unit)}</td><td>${i.grossWeight}</td><td>${i.netWeight}</td><td>${money(i.grossValue)}</td><td>${money(i.netValue)}</td><td>${esc(i.supplier)}</td><td>${i.stock}</td><td><b>${best?money(best.price):"—"}</b><small class="block">${best?esc(best.supplier):""}</small></td><td><button class="icon-btn" onclick="editIng(${i.id})">✎</button><button class="icon-btn delete" onclick="delIng(${i.id})">×</button></td></tr>`}).join("");}
function stock(){const val=S.ingredients.reduce((a,i)=>a+i.stock*i.price,0),low=S.ingredients.filter(i=>i.stock<=i.min).length;$("stockValue").textContent=money(val);$("stockCount").textContent=S.ingredients.length;$("stockCritical").textContent=low;const q=($("stockSearch").value||"").toLowerCase();$("stockTable").innerHTML=S.ingredients.filter(i=>i.name.toLowerCase().includes(q)).map(i=>`<tr><td>${esc(i.name)}</td><td>${esc(i.category)}</td><td>${i.stock}</td><td>${esc(i.unit)}</td><td>${money(i.price)}</td><td>${money(i.stock*i.price)}</td><td><span class="tag ${i.stock<=i.min?"low":"ok"}">${i.stock<=i.min?"Repor":"OK"}</span></td><td><button class="icon-btn" onclick="move(${i.id})">Mov.</button></td></tr>`).join("");}
function recipes(){
 $("recipeGrid").innerHTML=S.products.map(p=>{const img=p.image?`<div class="recipe-image-wrap"><img class="recipe-image" id="img-${p.id}" src="${p.image}" style="transform:scale(${zoomState[p.id]||1})"></div><div class="image-controls"><button class="zoom-btn" data-id="${p.id}" data-dir="in">+</button><button class="zoom-btn" data-id="${p.id}" data-dir="out">−</button><button class="zoom-btn" data-id="${p.id}" data-dir="reset">⟲</button></div>`:`<div class="recipe-image-placeholder">Sem imagem</div>`;return `<article class="recipe"><div class="panel-title"><div><h3>${esc(p.name)}</h3><span class="badge">${p.sold||0} vendidos</span></div><button class="icon-btn" onclick="editProduct(${p.id})">✎</button></div><div class="recipe-price">${money(p.price)}</div>${img}<p class="recipe-description">${esc(p.description||"Sem descrição.")}</p>${(p.recipe||[]).map(r=>`<div class="recipe-line"><span>${esc(ing(r.i)?.name||"—")} × ${r.q}</span><b>${money((ing(r.i)?.price||0)*r.q)}</b></div>`).join("")}<div class="recipe-total"><span>Custo ingredientes</span><b>${money(cost(p))}</b></div><div class="recipe-total"><span>CMO + embalagem</span><b>${money(cmo(p))}</b></div><div class="recipe-total"><span>Custo total</span><b>${money(totalProductCost(p))}</b></div><div class="recipe-total"><span>CMV</span><b>${pct(cmv(p))}</b></div><div class="recipe-total"><span>Markup</span><b>${markup(p).toFixed(2)}x</b></div><div class="recipe-total"><span>Margem unitária</span><b>${money(margin(p))}</b></div></article>`}).join("");document.querySelectorAll(".zoom-btn").forEach(btn=>btn.onclick=function(){const id=+this.dataset.id,dir=this.dataset.dir;zoomState[id]=zoomState[id]||1;if(dir==="in")zoomState[id]=Math.min(3,zoomState[id]+.1);if(dir==="out")zoomState[id]=Math.max(.3,zoomState[id]-.1);if(dir==="reset")zoomState[id]=1;const img=$("img-"+id);if(img)img.style.transform=`scale(${zoomState[id]})`;});}
function products(){$("productTable").innerHTML=S.products.map(p=>`<tr><td>${esc(p.name)}</td><td>${money(p.price)}</td><td>${money(cost(p))}</td><td>${pct(cmv(p))}</td><td>${money(cmo(p))}</td><td>${markup(p).toFixed(2)}x</td><td>${money(margin(p))}</td><td>${p.sold||0}</td><td><button class="icon-btn" onclick="editProduct(${p.id})">✎</button><button class="icon-btn delete" onclick="delProduct(${p.id})">×</button></td></tr>`).join("");}
function reports(){const rev=revenueFromSales(S.sales),c=S.sales.reduce((a,s)=>a+cost(prod(s.product)||{})*s.qty,0);$("profitTable").innerHTML=S.products.slice().sort((a,b)=>cmv(a)-cmv(b)).map(p=>`<tr><td>${esc(p.name)}</td><td>${money(p.price)}</td><td>${money(totalProductCost(p))}</td><td>${money(cmo(p))}</td><td>${money(margin(p))}</td><td>${pct(cmv(p))}</td></tr>`).join("");const qty=S.sales.reduce((a,s)=>a+s.qty,0);$("indicators").innerHTML=[["Faturamento por vendas",money(rev)],["CMV teórico",pct(rev?c/rev*100:0)],["Ticket médio",money(qty?rev/qty:0)],["Melhor margem unitária",esc([...S.products].sort((a,b)=>margin(b)-margin(a))[0]?.name||"—")],["Produtos cadastrados",S.products.length],["Insumos cadastrados",S.ingredients.length]].map(x=>`<div class="indicator"><span>${x[0]}</span><b>${x[1]}</b></div>`).join("");}
function purchases(){$("purchaseTable").innerHTML=S.purchases.slice().reverse().map(p=>`<tr><td>${p.date}</td><td>${esc(ing(p.i)?.name||"—")}</td><td>${p.q}</td><td>${money(p.unit)}</td><td>${money(p.q*p.unit)}</td><td>${esc(p.supplier||"—")}</td><td><button class="icon-btn delete" onclick="delPurchase(${p.id})">×</button></td></tr>`).join("");}
function vendasProduto(){
 const vp=$("vpProduct"),old=vp.value;vp.innerHTML=`<option value="all">Todos os produtos</option>`+S.products.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join("");if(old)vp.value=old;
 const now=new Date();const def=now.toISOString().slice(0,7);if(!$("vpMonth").value)$("vpMonth").value=def;const prev=new Date(now.getFullYear(),now.getMonth()-1,1).toISOString().slice(0,7);if(!$("vpCompareMonth").value)$("vpCompareMonth").value=prev;renderVendasProduto();}
function renderVendasProduto(){const pid=$("vpProduct").value||"all",m=$("vpMonth").value||today().slice(0,7),cm=$("vpCompareMonth").value||"";const filter=(s,month)=>s.date.slice(0,7)===month&&(pid==="all"||s.product==pid);const current=S.sales.filter(s=>filter(s,m)),compare=S.sales.filter(s=>filter(s,cm));const q=current.reduce((a,s)=>a+s.qty,0),rev=revenueFromSales(current),cq=compare.reduce((a,s)=>a+s.qty,0),variation=cq?((q-cq)/cq*100):(q?100:0);$("vpQty").textContent=q;$("vpRevenue").textContent=money(rev);$("vpVariation").textContent=pct(variation);if(charts.vp)charts.vp.destroy();const labels=[cm,m],data=[cq,q];charts.vp=new Chart($("vendasProdutoChart"),{type:"bar",data:{labels,datasets:[{label:pid==="all"?"Unidades":"Produto selecionado",data}]},options:{responsive:true,plugins:{legend:{position:"bottom"}}}});
 const rows=S.products.map(p=>{const a=S.sales.filter(s=>s.product==p.id&&s.date.slice(0,7)===m).reduce((x,s)=>x+s.qty,0),b=S.sales.filter(s=>s.product==p.id&&s.date.slice(0,7)===cm).reduce((x,s)=>x+s.qty,0),v=b?((a-b)/b*100):(a?100:0);return {p,a,b,v};}).sort((a,b)=>b.a-a.b);$("vendasProdutoTable").innerHTML=rows.map(x=>`<tr><td>${esc(x.p.name)}</td><td>${x.a}</td><td>${x.b}</td><td>${pct(x.v)}</td><td><span class="tag ${x.a>x.b?"ok":x.a<x.b?"low":"neutral"}">${x.a>x.b?"Cresceu":x.a<x.b?"Caiu":"Igual"}</span></td></tr>`).join("");}
function config(){$("cfgLabor").value=S.config.labor;$(`cfgFixed`).value=S.config.fixed;$(`cfgTarget`).value=S.config.target;}
function newSale(){modal("Registrar venda",`<div class="form-grid"><label>Data<input name="date" type="date" value="${today()}" required></label><label>Produto<select name="product">${S.products.map(p=>`<option value="${p.id}">${esc(p.name)} — ${money(p.price)}</option>`).join("")}</select></label><label>Quantidade<input name="qty" type="number" min="1" value="1" required></label></div><button class="primary">Registrar</button>`,d=>{const p=prod(d.get("product")),q=+d.get("qty"),date=d.get("date");if(!p)return;S.sales.push({id:Date.now(),date,product:p.id,qty:q});p.sold=(p.sold||0)+q;S.transactions.push({id:Date.now()+1,date,dueDate:date,type:"entrada",cat:"Vendas",paymentMethod:"Outros",desc:p.name,value:p.price*q,status:"pago"});(p.recipe||[]).forEach(r=>{const i=ing(r.i);if(i)i.stock=Math.max(0,i.stock-r.q*q);});save();toast("Venda registrada e estoque baixado");render();});}
function newTx(){
 const catsIn=S.financeCategories.entrada,catsOut=S.financeCategories.saida;
 modal("Novo lançamento",`<div class="form-row"><label>Data<input name="date" type="date" value="${today()}" required></label><label>Vencimento<input name="dueDate" type="date" value="${today()}" required></label></div><div class="form-row"><label>Tipo<select name="type" id="txType"><option value="entrada">Entrada — Receita</option><option value="saida">Saída — Despesa</option></select></label><label>Categoria/forma<select name="cat" id="txCat"></select></label></div><label>Forma de recebimento/pagamento<select name="paymentMethod"><option>Pix</option><option>Dinheiro</option><option>Cartão</option><option>Goomer</option><option>iFood</option><option>WhatsApp</option><option>Outros</option></select></label><label>Descrição<input name="desc" required></label><div class="form-row"><label>Valor<input name="value" type="number" step=".01" min="0" required></label><label>Status<select name="status"><option value="pago">Pago/Recebido</option><option value="pendente">Pendente/A vencer</option></select></label></div><button class="primary">Salvar</button>`,d=>{S.transactions.push({id:Date.now(),date:d.get("date"),dueDate:d.get("dueDate"),type:d.get("type"),cat:d.get("cat"),paymentMethod:d.get("paymentMethod"),desc:d.get("desc"),value:+d.get("value"),status:d.get("status")});save();toast("Lançamento salvo");render();});
 setTimeout(()=>{const type=$("txType"),cat=$("txCat");function fill(){const arr=type.value==="entrada"?S.financeCategories.entrada:S.financeCategories.saida;cat.innerHTML=arr.map(x=>`<option>${esc(x)}</option>`).join("");}type.onchange=fill;fill();},20);
}
function newIngredient(old){let i=old||{id:Date.now(),name:"",category:"Alimentos",unit:"kg",price:0,supplier:"",stock:0,min:0,grossWeight:1,netWeight:1,grossValue:0,netValue:0,marketPrices:[]};const mp=i.marketPrices||[];const fields=[...mp,...Array(Math.max(0,4-mp.length)).fill({})].slice(0,4).map((m,n)=>`<div class="form-row"><label>Fornecedor ${n+1}<input name="mktSupplier${n}" value="${esc(m.supplier||"")}"></label><label>Preço ${n+1}<input name="mktPrice${n}" type="number" step=".0001" value="${m.price??""}"></label></div>`).join("");modal(old?"Editar insumo":"Novo insumo",`<div class="form-row"><label>Produto<input name="name" value="${esc(i.name)}" required></label><label>Categoria<input name="category" list="ingredientCats" value="${esc(i.category)}"><datalist id="ingredientCats"><option>Alimentos</option><option>Embalagens</option><option>Limpeza</option><option>Bebidas</option><option>Administrativo</option><option>Outros</option></datalist></label></div><div class="form-row"><label>Unidade referência<select name="unit"><option ${i.unit==="kg"?"selected":""}>kg</option><option ${i.unit==="g"?"selected":""}>g</option><option ${i.unit==="L"?"selected":""}>L</option><option ${i.unit==="ml"?"selected":""}>ml</option><option ${i.unit==="un"?"selected":""}>un</option><option ${i.unit==="cx"?"selected":""}>cx</option><option ${i.unit==="pct"?"selected":""}>pct</option></select></label><label>Fornecedor principal<input name="supplier" value="${esc(i.supplier)}"></label></div><div class="form-row"><label>Peso bruto<input name="grossWeight" type="number" step=".001" value="${i.grossWeight}"></label><label>Peso líquido<input name="netWeight" type="number" step=".001" value="${i.netWeight}"></label></div><div class="form-row"><label>Valor bruto<input name="grossValue" type="number" step=".0001" value="${i.grossValue}"></label><label>Valor líquido<input name="netValue" type="number" step=".0001" value="${i.netValue}"></label></div><div class="form-row"><label>Estoque atual<input name="stock" type="number" step=".001" value="${i.stock}"></label><label>Estoque mínimo<input name="min" type="number" step=".001" value="${i.min}"></label></div><h4>Comparação de fornecedores</h4>${fields}<button class="primary">Salvar insumo</button>`,d=>{const prices=[];for(let n=0;n<4;n++){const supplier=d.get(`mktSupplier${n}`),price=parseFloat(d.get(`mktPrice${n}`));if(supplier&&!isNaN(price)&&price>=0)prices.push({supplier,price});}Object.assign(i,{name:d.get("name"),category:d.get("category")||"Outros",unit:d.get("unit"),supplier:d.get("supplier"),grossWeight:+d.get("grossWeight"),netWeight:+d.get("netWeight"),grossValue:+d.get("grossValue"),netValue:+d.get("netValue"),price:+d.get("netValue"),stock:+d.get("stock"),min:+d.get("min"),marketPrices:prices});if(!old)S.ingredients.push(i);save();toast("Insumo salvo");render();});}
function newPurchase(){modal("Nova compra",`<label>Data<input name="date" type="date" value="${today()}"></label><label>Insumo<select name="i">${S.ingredients.map(i=>`<option value="${i.id}">${esc(i.name)}</option>`).join("")}</select></label><div class="form-row"><label>Quantidade<input name="q" type="number" step=".001" min=".001" required></label><label>Preço unitário<input name="unit" type="number" step=".0001" min="0" required></label></div><label>Fornecedor<input name="supplier"></label><button class="primary">Registrar compra</button>`,d=>{const q=+d.get("q"),u=+d.get("unit"),i=ing(d.get("i"));if(!i)return;i.stock+=q;i.price=u;i.netValue=u;S.purchases.push({id:Date.now(),date:d.get("date"),i:+d.get("i"),q,unit:u,supplier:d.get("supplier")});S.transactions.push({id:Date.now()+1,date:d.get("date"),dueDate:d.get("date"),type:"saida",cat:"Mercado",paymentMethod:"Pix",desc:"Compra de "+i.name,value:q*u,status:"pago"});save();toast("Compra registrada e estoque atualizado");render();});}
function move(id){const i=ing(id);if(!i)return;modal("Movimentar estoque",`<label>Insumo<input value="${esc(i.name)}" disabled></label><div class="form-row"><label>Tipo<select name="type"><option value="in">Entrada</option><option value="out">Saída</option><option value="loss">Perda</option></select></label><label>Quantidade<input name="q" type="number" step=".001" min=".001" required></label></div><button class="primary">Aplicar</button>`,d=>{const q=+d.get("q");i.stock=Math.max(0,i.stock+(d.get("type")==="in"?q:-q));save();toast("Estoque atualizado");render();});}
function newProduct(old){
 let p=old||{id:Date.now(),name:"",price:0,sold:0,recipe:[],image:"",description:"",laborCost:0,packagingCost:0,yield:1};
 const imageHtml=`<label>Imagem da ficha (PNG/JPG)<input type="file" accept="image/png,image/jpeg" id="productImageInput"><div id="imagePreview" class="image-preview">${p.image?`<img src="${p.image}">`:"Sem imagem"}</div></label>`;
 const rows=(p.recipe.length?p.recipe:[{i:S.ingredients[0]?.id,q:0}]).map((r,n)=>`<div class="form-row r"><label>Insumo<select name="i${n}">${S.ingredients.map(i=>`<option value="${i.id}" ${i.id==r.i?"selected":""}>${esc(i.name)}</option>`).join("")}</select></label><label>Quantidade<input name="q${n}" type="number" step=".001" value="${r.q}"></label></div>`).join("");
 modal(old?"Editar ficha técnica":"Nova ficha técnica",`<div class="form-row"><label>Produto<input name="name" value="${esc(p.name)}" required></label><label>Preço de venda<input name="price" type="number" step=".01" value="${p.price}"></label></div><div class="form-row"><label>Rendimento<input name="yield" type="number" step=".01" value="${p.yield||1}"></label><label>Unidades já vendidas<input name="sold" type="number" value="${p.sold||0}"></label></div><label>Descrição da receita<textarea name="description" rows="4">${esc(p.description||"")}</textarea></label><div class="form-row"><label>CMO por unidade<input name="laborCost" type="number" step=".01" value="${p.laborCost||0}"></label><label>Embalagem por unidade<input name="packagingCost" type="number" step=".01" value="${p.packagingCost||0}"></label></div>${imageHtml}<h4>Ingredientes</h4><div id="recipeFields">${rows}</div><button type="button" class="secondary" id="addIngRow">+ Ingrediente</button><button class="primary">Salvar ficha</button>`,d=>{const file=$("productImageInput")?.files?.[0];function finish(){const rs=[...document.querySelectorAll("#recipeFields .r")].map((el,n)=>({i:+d.get("i"+n),q:+d.get("q"+n)})).filter(x=>x.i&&x.q>0);Object.assign(p,{name:d.get("name"),price:+d.get("price"),sold:+d.get("sold"),yield:+d.get("yield")||1,description:d.get("description"),laborCost:+d.get("laborCost")||0,packagingCost:+d.get("packagingCost")||0,recipe:rs});if(!old)S.products.push(p);save();toast("Ficha técnica salva");render();}if(file){const reader=new FileReader();reader.onload=e=>{const img=new Image();img.onload=()=>{const c=document.createElement("canvas"),ratio=Math.min(900/img.width,900/img.height,1);c.width=Math.round(img.width*ratio);c.height=Math.round(img.height*ratio);c.getContext("2d").drawImage(img,0,0,c.width,c.height);p.image=c.toDataURL("image/jpeg",.86);finish();};img.src=e.target.result;};reader.readAsDataURL(file);}else finish();});
 setTimeout(()=>{$("productImageInput")?.addEventListener("change",e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=x=>{$("imagePreview").innerHTML=`<img src="${x.target.result}">`;};r.readAsDataURL(f);});$("addIngRow")?.addEventListener("click",()=>{const n=document.querySelectorAll("#recipeFields .r").length;$("recipeFields").insertAdjacentHTML("beforeend",`<div class="form-row r"><label>Insumo<select name="i${n}">${S.ingredients.map(i=>`<option value="${i.id}">${esc(i.name)}</option>`).join("")}</select></label><label>Quantidade<input name="q${n}" type="number" step=".001" value="0"></label></div>`);});},50);
}
function manageFinanceCategories(){modal("Categorias financeiras",`<p class="muted">Digite uma categoria por linha. As alterações ficam salvas no navegador.</p><div class="form-row"><label>Receitas<textarea name="entrada" rows="10">${esc(S.financeCategories.entrada.join("\n"))}</textarea></label><label>Despesas<textarea name="saida" rows="10">${esc(S.financeCategories.saida.join("\n"))}</textarea></label></div><button class="primary">Salvar categorias</button>`,d=>{S.financeCategories.entrada=d.get("entrada").split("\n").map(x=>x.trim()).filter(Boolean);S.financeCategories.saida=d.get("saida").split("\n").map(x=>x.trim()).filter(Boolean);save();toast("Categorias atualizadas");render();});}
window.delSale=id=>{if(confirm("Excluir venda? O estoque não será estornado automaticamente.")){S.sales=S.sales.filter(x=>x.id!==id);save();render();}};
window.delTx=id=>{if(confirm("Excluir lançamento?")){S.transactions=S.transactions.filter(x=>x.id!==id);save();render();}};
window.toggleTxStatus=id=>{const t=S.transactions.find(x=>x.id==id);if(t){t.status=t.status==="pago"?"pendente":"pago";save();render();}};
window.editIng=id=>newIngredient(ing(id));window.delIng=id=>{if(confirm("Excluir insumo?")){S.ingredients=S.ingredients.filter(x=>x.id!=id);save();render();}};window.move=move;window.editProduct=id=>newProduct(prod(id));window.delProduct=id=>{if(confirm("Excluir produto?")){S.products=S.products.filter(x=>x.id!=id);save();render();}};window.delPurchase=id=>{if(confirm("Excluir compra do histórico? Isso não desfaz o estoque.")){S.purchases=S.purchases.filter(x=>x.id!=id);save();render();}};
function backup(){const a=document.createElement("a"),b=new Blob([JSON.stringify(S,null,2)],{type:"application/json"});a.href=URL.createObjectURL(b);a.download="mix-chicken-backup.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);}
function exportSalesCsv(){const m=$("vpMonth").value,cm=$("vpCompareMonth").value;const rows=[["Produto",m,cm,"Variação %"]];S.products.forEach(p=>{const a=S.sales.filter(s=>s.product==p.id&&s.date.slice(0,7)===m).reduce((x,s)=>x+s.qty,0),b=S.sales.filter(s=>s.product==p.id&&s.date.slice(0,7)===cm).reduce((x,s)=>x+s.qty,0),v=b?((a-b)/b*100):(a?100:0);rows.push([p.name,a,b,v.toFixed(1)]);});const csv=rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(";")).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));a.download="vendas-por-produto.csv";a.click();}
function render(){dashboard();sales();finance();ingredients();stock();recipes();products();reports();config();purchases();vendasProduto();}
buildNav();
$("newSale").onclick=newSale;$("quickSale").onclick=newSale;$("newTx").onclick=newTx;$("newIngredient").onclick=()=>newIngredient();$("newPurchase").onclick=newPurchase;$("newMovement").onclick=()=>move(S.ingredients[0]?.id);$("newProduct").onclick=()=>newProduct();$("newProduct2").onclick=()=>newProduct();$("manageFinanceCategories").onclick=manageFinanceCategories;$("exportSalesCsv").onclick=exportSalesCsv;$("dashboardProductCompare").onchange=e=>renderProductCompare(e.target.value);$("vpProduct").onchange=renderVendasProduto;$("vpMonth").onchange=renderVendasProduto;$("vpCompareMonth").onchange=renderVendasProduto;$("plannerWeek").onchange=planner;
$("period").onchange=function(){if(this.value==="-1")$("customDateRange").classList.add("show-range");else{$("customDateRange").classList.remove("show-range");customStart=customEnd=null;render();}};$("applyCustomPeriod").onclick=()=>{customStart=$("customStartDate").value;customEnd=$("customEndDate").value;if(customStart&&customEnd)render();else toast("Selecione as duas datas");};
["saleSearch","txSearch","ingredientSearch","stockSearch"].forEach(id=>$(id).oninput=render);
$("saveCfg").onclick=()=>{S.config.labor=+$(`cfgLabor`).value;S.config.fixed=+$(`cfgFixed`).value;S.config.target=+$(`cfgTarget`).value;save();toast("Configurações salvas");render();};$("exportBtn").onclick=backup;$("export2").onclick=backup;$("importBtn").onclick=()=>$("fileInput").click();$("fileInput").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader;r.onload=()=>{try{S=JSON.parse(r.result);migrate();render();toast("Backup restaurado");}catch{toast("Arquivo inválido");}};r.readAsText(f);};$("reset").onclick=()=>{if(confirm("Restaurar dados de demonstração? Isso substitui os dados atuais deste navegador.")){S=structuredClone(DEMO);save();render();toast("Dados restaurados");}};$("printReport").onclick=()=>window.print();
go("dashboard");
